  const resInfo = {
    SERVICE: "FMAVTS-TripMicroService",
    TRIP_PLAN: "Hurray! New Trip is being planned",
    TRIP_FPLAN: "Unable to create trip, Please try again later",
    TRIP_UPDATE: "Trip Details Updated Successfully!",
    TRIP_DELETE: "Trip Deleted successfully",
    TRIP_UPDATE_FAIL: "Unable to update trip details, Try Again!",
    TRIP_DELETE_FAIL: "Unable to delete trip",
    TRIP_STATUS: "Trip status has been updated successfully!",
    TRIP_FSTATUS: "Unable to update trip status",
    IN_STATUS: "in-progress",
    ALLTRIPS: "Trips details fetched Successfully",
    TRIPS_DATA_NA: "No trips are available till date",
    ACCESS_DENIED: "You do not have the required permissions to perform this action; please contact support or an administrator for assistance if you believe this is an error",
    ROLE_VALIDATION_FAIL: "user role validation failed",
    ERROR_VALIDATING_ROLE: "Role validation failed due to issue at server Please try again after some time",
    ROLE_VALIDATION: "user role validation success",
    CONN_USER_SERVICE: "Initiating connection to User Service....",
    CONN_USER_SERVICE_SUCC: "User data successfully retrieved from User Service",
    D_STATUS: "active",
    TRIP_INP: "in-progress",
    TRIP_CNC: "cancelled",
    TRIP_COMP: "completed",
    CD_NOT_ACTIVE: "Current Driver you are looking at is busy at the moment, Please try with a different one",
    UPTSTS_INP: "Update trip status to in-progress is successfull 🚨",
    UPTSTS_CNC: "Trip status has been set to cancelled with cancellation status ❌",
    UPTSTS_CMP: "Trip status has been marked as completed ✅",
    DELAY_CHECK: "verifying delay ⏱️ status for trip Id",
    DELAY_CONFIRMED: "Trip has been delayed by",
    DELAY_NTCNF: "Hurray, Trip has completed on time 🔥",
    TO_LOGO: "➡️",
    QUEUE_CONN_SUCESS: "Queue connection successfull",
    QUEUE_CON_FAIL: "Connection to message-queue Failed",
    QUEUE_CON_CLOSE: "Queue Connection closed",
    USER_EVENT: "Driver availiability status to driver service sent successfully",
    DRIVER_MSG_QUEUE: "Publish-Driver-Activity-Details",
    DRIVER_ACTIVITY_DETAILS_SENT_TO_QUEUE: "Driver Activity Details has been sent to queue for further action",
    DRIVER_BUSY_STATUS: "busy",
    DRIVER_ACTIVE_STATUS: "active",
    DRIVER_TRIP_QUEUE: "Publish-Completed-Trip-Details",
    TRIP_INFO_EVENT:"Trip details has been sent to vehicle service to update details"
  
  }

  module.exports = resInfo;